### ISSUE TITLE
Damaged files for inputs 1995 and pristine outputs 1851

### ISSUE THREAD

**Issue by ArsamAryandoust** [RolnickLab/climart#1]
When downloading data and trying to load them with the h5py.File() class/function of the h5py package in python, there occurs an error. 

All other data files work flawlessly. Several tests have been conducted to ensure there is no damaged file problems during download.

**Comment by ArsamAryandoust** [comment]
@Venka97  and @salvaRC

**Comment by Venka97** [comment]
Hi @ArsamAryandoust, you're right there seems to be an error with some files (likely caused by our cloud hosting service.) We're working on regenerating the dataset and will be uploading those on the server soon!

**Comment by ArsamAryandoust** [comment]
@Venka97 @salvaRC  Cool, it would be great if you give a short notice when this is done. Also, you may want to check out how my team and I are currently using your data here: https://github.com/ArsamAryandoust/EnergyTransitionTasks

I btw really enjoyed reading your paper. I find it really well written! Good job!

**Comment by Venka97** [comment]
Hi @ArsamAryandoust, we'll keep you updated. Running the simulation from the climate model takes a while so it might take a few weeks.

Your repository looks really cool! I see that you're interested in downscaling too :)

I also worked on downscaling recently. If you would like to check it out, you can find it here: https://arxiv.org/pdf/2208.05424.pdf

**Comment by ArsamAryandoust** [comment]
Hi @Venka97. Thanks for the reference. That's indeed the dataset I am integrating! 

I will close this issue and follow your update.
